### ISSUE TITLE
Review 20170426 (commit  0924b6d)

### ISSUE THREAD

**Issue by nthtson** [prdlab/wrappy.net#2]
Layout: 
- Horizontal scroll on landing page (desktop screen)
- On hover action, menu item background is black, it should be the same as active item background.
- "ABOUT US" content is left now (css should be *text-align: justify*)
- "CONTACT" placeholder texts, use "Your name, Your email..." or "Enter name, Enter email....". Currently, they're displayed in 3 ways (Your name, Enter email and Message).
- "INTRODUCE APP" js effect isn't working well (same on "FAQ").

HTML/CSS:
- Shouldn't define class names: "new_header" (should be new-header, _ is for better ID). Please ref: http://getbem.com/naming/
- Please don't use Vietnamese to comment-in in files.
- In "less" folder, please remove CSS files.
- Define less variable name as "brand-color" (not "brandColor").

**Comment by AnhNDT** [comment]
done
